Project17/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

Project17/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
]

Project17/til/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    url("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project17/feed/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.text[0:100]

Project17/followers/models.py
from django.db import models
from django.contrib.auth.models import User


class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='followed_by'
    )
    following = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return f"{self.followed_by.id} is following {self.following.id}"

    class Meta:
        unique_together = ('followed_by', 'following',)

Project17/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        Profile.objects.create(user=instance)

Project17/feed/views.py
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from followers.models import Follower

from .models import Post


class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            following = list(
                Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True)
            )
            if not following:
                # Show the default 30
                posts = Post.objects.all().order_by('-id')[0:30]
            else:
                posts = Post.objects.filter(author__in=following).order_by('-id')[0:60]
        else:
            posts = Post.objects.all().order_by('-id')[0:30]
        context['posts'] = posts
        return context


class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"


class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text']
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        # TODO: There is a bug here when you go to /new/ to create a post.
        # You must figure out how to determine if this is an Ajax request (or not an ajax request).
        post = Post.objects.create(
            text=request.POST.get("text"),
            author=request.user,
        )

        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True,
            },
            content_type="application/html"
        )

Project17/followers/views.py
from django.shortcuts import render

# Create your views here.

Project17/profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest

from feed.models import Post
from followers.models import Follower


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        # context['total_followers'] = ...
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context


class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            # Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

Project17/feed/templates/feed/create.html
{% extends "base.html" %}

{% block title %}Create a new post{% endblock title %}

{% block body %}
    <form method="POST" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <div class="my-3">
                <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
                    <span class="mr-2">Create Post</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </form>
{% endblock body %}

Project17/feed/templates/feed/detail.html
{% extends "base.html" %}

{% block title %}{{ post.text }} by {{ post.author.username }}{% endblock %}

{% block body %}
    {% include "includes/post.html" with post=post %}
{% endblock body %}

Project17/feed/templates/feed/homepage.html
{% extends "base.html" %}

{# TODO: Change title text #}
{% block title %}Changed the title of the homepage{% endblock %}

{% block body %}
    <div id="posts-container">
        {% for post in posts %}
            {% include "includes/post.html" with post=post show_detail_link=True %}
        {% endfor %}
    </div>
{% endblock %}

Project17/profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ user.username }}{% endblock title %}

{% block body %}
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
  	<img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profile.image "100x100" crop="center" as im %}
            <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
	<div class="text-center px-3 pb-6 pt-2">
		<h3 class="text-black text-sm bold font-sans">{{ user.username }}</h3>
        {% if request.user.is_authenticated %}
            {% if request.user != user %}
                <div class="mt-3">
                    <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 text-xs inline-flex items-center js-follow" data-username="{{ user.username }}" data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}" type="button">
                        <span class="mr-2 js-follow-text">
                            {% if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="mt-3 text-sm">Login to follow this user</div>
        {% endif %}
	</div>
  	<div class="flex justify-center pb-3 text-grey-dark">
      <div class="text-center mr-3 border-r pr-3">
        <h2>{{ total_posts }}</h2>
        <span>Posts</span>
      </div>
      <div class="text-center">
        <h2>xx {# TODO: Add total followers #}</h2>
        <span>Followers</span>
      </div>
  	</div>
</div>
{% endblock body %}

Project17/til/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title in here{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>
<body>

<!-- component is from https://tailwindcomponents.com/component/sidebar-navigation -->
<div class="min-h-screen flex flex-row bg-gray-100">
  <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
      <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
    </div>
    <ul class="flex flex-col py-4">
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
          <span class="text-sm font-medium">Home</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'feed:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800 js-toggle-modal">
              <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-layer-plus"></i></span>
              <span class="text-sm font-medium">New post</span>
            </a>
        </li>
        <li>
            <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
            <span class="text-sm font-medium">Logout</span>
            </a>
        </li>
      {% else %}
        <li>
            <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
            <span class="text-sm font-medium">Login</span>
            </a>
        </li>
      {% endif %}
    </ul>
  </div>
  <div class="p-16">
    {% block body %}
        {% block content %}{% endblock %}
    {% endblock %}
  </div>


{% if request.user.is_authenticated %}
  {# TODO: Move the modal into an included file in order to keep base.html clean and organized #}
  <!-- component -->
  <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 hidden js-modal">
    <div class="bg-white rounded-lg w-1/2">
      <div class="flex flex-col items-start p-4">
        <div class="flex items-center w-full">
          <div class="text-gray-900 font-medium text-lg">New post</div>
      <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
        </svg>
        </div>
        <hr>
        <div class="w-full">
          <textarea class="border-2 border-blue-500 my-4 w-full js-post-text" placeholder="Enter your post" rows="3" maxlength="240" data-post-url="{% url 'feed:new_post' %}"></textarea>
        </div>
        <hr>
        <div class="ml-auto">
          <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit" type="button">
              <span class="mr-2">Create Post</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
              </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>


</body>
</html>

Project17/til/templates/includes/post.html
{% load thumbnail %}

<!-- component is from https://tailwindcomponents.com/component/post-artical -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 50rem'>
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{ post.text }}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
                Read more
            </a>
        {% else %}
            <span>&nbsp;</span>
        {% endif %}
        <div>
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                    <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>
    </div>
</div>